[package]
name = "OnePet"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }
MoveStdlib = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "main" }

[addresses]
one = "0x2"
OnePet = "0x0"
